# Generated by Django 3.0.1 on 2020-06-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20200610_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_line',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='pincode',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
