# Generated by Django 3.0.1 on 2020-06-24 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cart', '0003_order_no_for_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
                ('user_email', models.EmailField(max_length=254)),
                ('product_name', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=8)),
                ('order_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.Order_No_For_User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
