# Generated by Django 3.0.1 on 2020-04-30 09:24

import Company.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_email', models.EmailField(max_length=254, unique=True)),
                ('c_name', models.CharField(max_length=50)),
                ('c_phone', models.CharField(max_length=10)),
                ('c_street', models.TextField()),
                ('c_area', models.TextField()),
                ('c_city', models.TextField()),
                ('c_state', models.TextField()),
                ('c_country', models.TextField()),
                ('c_pincode', models.CharField(max_length=6)),
                ('c_logo', models.ImageField(upload_to=Company.models.upload_image_path)),
                ('c_website', models.URLField()),
                ('c_linkedin', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50, unique=True)),
                ('c_email', models.EmailField(max_length=254)),
                ('c_password', models.CharField(max_length=16)),
                ('c_r_password', models.CharField(max_length=16)),
                ('c_verification_flag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_company_id', models.CharField(max_length=20)),
                ('p_name', models.CharField(max_length=50)),
                ('p_model_no', models.CharField(max_length=20)),
                ('p_bio', models.TextField()),
                ('p_manufacturing_date', models.DateField()),
                ('p_img_1', models.ImageField(upload_to=Company.models.upload_product_img_path)),
                ('p_img_2', models.ImageField(upload_to=Company.models.upload_product_img_path)),
                ('p_img_3', models.ImageField(blank=True, null=True, upload_to=Company.models.upload_product_img_path)),
                ('p_img_4', models.ImageField(blank=True, null=True, upload_to=Company.models.upload_product_img_path)),
                ('p_img_5', models.ImageField(blank=True, null=True, upload_to=Company.models.upload_product_img_path)),
                ('p_img_6', models.ImageField(blank=True, null=True, upload_to=Company.models.upload_product_img_path)),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('P_warranty', models.DecimalField(decimal_places=2, max_digits=4)),
                ('p_replace_time', models.CharField(max_length=3)),
                ('p_ppt', models.FileField(blank=True, null=True, upload_to=Company.models.upload_ppt_path)),
                ('p_pdf', models.FileField(blank=True, null=True, upload_to=Company.models.upload_pdf_path)),
                ('p_blog_link', models.URLField(blank=True, null=True)),
                ('p_youtube_link', models.URLField(blank=True, null=True)),
                ('p_software_link', models.URLField(blank=True, null=True)),
                ('p_feature_1', models.CharField(max_length=300)),
                ('p_feature_2', models.CharField(max_length=300)),
                ('p_feature_3', models.CharField(blank=True, max_length=300, null=True)),
                ('p_feature_4', models.CharField(blank=True, max_length=300, null=True)),
                ('p_feature_5', models.CharField(blank=True, max_length=300, null=True)),
                ('p_feature_6', models.CharField(blank=True, max_length=300, null=True)),
                ('p_creation_date', models.DateTimeField(auto_now_add=True)),
                ('p_updated_date', models.DateTimeField(auto_now=True)),
                ('p_catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.Product_Catagory')),
            ],
        ),
    ]
