# Generated by Django 3.0.1 on 2020-05-31 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=50)),
                ('software_link', models.URLField()),
                ('youtube_link', models.URLField()),
                ('p_feature_1', models.CharField(max_length=300)),
                ('p_feature_2', models.CharField(max_length=300)),
                ('p_feature_3', models.CharField(blank=True, max_length=300, null=True)),
                ('p_feature_4', models.CharField(blank=True, max_length=300, null=True)),
                ('p_feature_5', models.CharField(blank=True, max_length=300, null=True)),
                ('hardware_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.Product_Hardware')),
            ],
        ),
    ]
