# Generated by Django 3.0.1 on 2020-06-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_product_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_software',
            name='company_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
