# Generated by Django 3.0.1 on 2020-06-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_auto_20200606_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='c_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
