# Generated by Django 3.0.1 on 2020-06-17 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0007_product_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_review',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product_review',
            old_name='user_id',
            new_name='user',
        ),
    ]
